# Generated by Django 2.2.6 on 2020-05-03 14:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserHasLessons',
            new_name='UserHasLesson',
        ),
    ]
