# Generated by Django 2.2.6 on 2020-05-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200503_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhascourse',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='userhascourse',
            name='periodicity',
            field=models.IntegerField(default=0),
        ),
    ]
