# Generated by Django 2.2.6 on 2020-05-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200503_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonhasimage',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='lessonhasimage',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='userhascourse',
            old_name='lesson_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='userhascourse',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userhaslesson',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='userhaslesson',
            old_name='user_id',
            new_name='user',
        ),
    ]
